from .kitchen_dinner_room import KitchenAndDinnerThermostat
from .bedroom import BedroomThermostat
from .small_bathroom import SmallBahtroomThermostat
from .living_room import LivingRoomThermostat
from .main_bathroom import MainBathroomThermostat
from .study_adele import StudyAdeleThermostat
from .study_mojmir import StudyMojmirThermostat
from .top_bathroom import TopBathroomThermostat
from .gym import GymThermostat
from .entrance import EntranceThermostat